fix: Fix "call to 'nwords' is ambiguous" error
fix bits::copyBits coredump caused by negative leafNullsSize_ (#529)
introduced nwords overload functions and this caused c++ failed with the
following error:

../../bolt/serializers/PrestoSerializer.cpp:2115:35: error: call to 'nwords' is ambiguous
 2115 |     auto* nulls = nullsHolder.get(bits::nwords(rows.size()));
      |                                   ^~~~~~~~~~~~

This commit fixes it by adding explict cast on the ambiguous callsites.